### ISSUE TITLE
Реализовать просмотр pdf-файлов для браузеров, не поддерживающих pdf-формат

### ISSUE THREAD

**Issue by kostrizzz** [DARKNEET69/deadly-lands#1]
![image](https://user-images.githubusercontent.com/106798921/192153792-d73b9339-2c57-4565-b847-01a67356b7e3.png)

**Comment by kostrizzz** [comment]
что изменилось то?

**Comment by DARKNEET69** [comment]
Бля, это че, вместо ссылки на пдфник придется прям хтмл страничку с текстом, таблицами и картинками хуячить, нихуя себе

**Comment by kostrizzz** [comment]
https://mozilla.github.io/pdf.js/ можно это попробовать заести
